faces/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'experiments/alexnet-filters$', views.alexnet_filters, name='alexnet-filters'),
        url(r'experiments/$', views.experiments, name='experiments'),
        url(r'progress/$', views.progress, name='progress'),
        url(r'related-work/eigenfaces/$', views.eigenfaces, name='eigenfaces'),
        url(r'related-work/$', views.related_work, name='related-work'),
        url(r'^cyclists/(?P<year>[a-z0-9]+)/(?P<gradient>[a-z]+)/(?P<stage>[a-z0-9]+)/$', 
            views.CyclistGalleryView.as_view(), name='cyclists-year-gradient-stage'),
        url(r'^cyclists/(?P<year>[a-z0-9]+)/(?P<gradient>[a-z]+)/$', views.CyclistGalleryView.as_view(), name='cyclists-year-gradient'),
        url(r'^cyclists/(?P<year>[0-9]+)/$', views.CyclistGalleryView.as_view(), name='cyclists-year'),
        url(r'^cyclists/$', views.CyclistGalleryView.as_view(), name='cyclists-all'),
]

grimaces/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('faces.urls', namespace='faces')),
    url(r'^sam/', include(admin.site.urls)),
]

faces/models.py
from django.db import models

class Face(models.Model):
    year = models.IntegerField(default=0)
    stage_num = models.IntegerField(default=0)
    gradient = models.FloatField(default=0)
    img_name = models.CharField(max_length=200)
    time = models.CharField(default=0, max_length=200)
    size = models.IntegerField(default=0)

    def __str__(self):
        return self.img_name
    

faces/views.py
from random import shuffle
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from django.utils import timezone
from django.conf import settings

from .models import Face
from .dataset_graphs import get_data_chart, get_binary_classification_chart
from .dataset_graphs import get_binary_class_boundary 
from .experiment_graphs import get_data_partition_chart
from .experiment_graphs import get_alexnet_binary_training_fig
from .experiment_graphs import get_alexnet_binary_testing_fig
from .experiment_graphs import get_alexnet_binary_ROC_fig
from .experiment_graphs import find_best_epoch, get_alexnet_data

def index(request):
    template = loader.get_template('faces/index.html')
    faces = get_num_faces(min_size=settings.MIN_FACE_SIZE)
    num_total_faces = (faces['2012']['num_faces'] +
                       faces['2013']['num_faces'] + 
                       faces['2014']['num_faces'] +
                       faces['2015']['num_faces'])
    data_chart = get_data_chart()
    context = RequestContext(request, {
        'num_total_faces': num_total_faces,
        'min_face_size': settings.MIN_FACE_SIZE,
        'num_faces_2012': faces['2012']['num_faces'],
        'min_gradient_2012': faces['2012']['min_gradient'],
        'max_gradient_2012': faces['2012']['max_gradient'],
        'num_faces_2013': faces['2013']['num_faces'],
        'min_gradient_2013': faces['2013']['min_gradient'],
        'max_gradient_2013': faces['2013']['max_gradient'],
        'num_faces_2014': faces['2014']['num_faces'],
        'min_gradient_2014': faces['2014']['min_gradient'],
        'max_gradient_2014': faces['2014']['max_gradient'],
        'num_faces_2015': faces['2015']['num_faces'],
        'min_gradient_2015': faces['2015']['min_gradient'],
        'max_gradient_2015': faces['2015']['max_gradient'],
        'chart': data_chart,
        })
    return HttpResponse(template.render(context))

def experiments(request):
    template = loader.get_template('faces/experiments.html')
    binary_class_boundary = get_binary_class_boundary()
    data_partition_chart = get_data_partition_chart()
    chart = get_binary_classification_chart()
    alexnet_binary_training_chart = get_alexnet_binary_training_fig()
    alexnet_binary_testing_chart = get_alexnet_binary_testing_fig()
    alexnet_binary_ROC_chart = get_alexnet_binary_ROC_fig()
    train, val = get_alexnet_data()
    best_epoch = find_best_epoch(val)
    context = RequestContext(request, {
        'data_partition_chart': data_partition_chart,
        'binary_classification_chart': chart,
        'binary_class_boundary': round(binary_class_boundary, 2),
        'alexnet_binary_training_chart': alexnet_binary_training_chart,
        'alexnet_binary_testing_chart': alexnet_binary_testing_chart,
        'alexnet_binary_ROC_chart': alexnet_binary_ROC_chart,
        'best_epoch': best_epoch,
        })
    return HttpResponse(template.render(context))

def related_work(request):
    template = loader.get_template('faces/related_work.html')
    binary_class_boundary = get_binary_class_boundary()
    chart = get_binary_classification_chart()
    context = RequestContext(request, {
        })
    return HttpResponse(template.render(context))

def eigenfaces(request):
    template = loader.get_template('faces/eigenfaces.html')
    context = RequestContext(request, {
        })
    return HttpResponse(template.render(context))

def alexnet_filters(request):
    template = loader.get_template('faces/alexnet_filters.html')
    context = RequestContext(request, {
        })
    return HttpResponse(template.render(context))

def progress(request):
    template = loader.get_template('faces/progress.html')
    context = RequestContext(request, {
        })
    return HttpResponse(template.render(context))

class CyclistGalleryView(generic.ListView):
    template_name = 'faces/cyclist_gallery.html'
    context_object_name = 'face_list'
    year = 'all'
    stage = 'all'
    gradient = 'random'
    paginate_by = 300

    def get_queryset(self, *args, **kwargs):
        """Return filtered subset of faces."""
        year = self.parse_year(self.kwargs)
        gradient = self.parse_gradient(self.kwargs)
        stage = self.parse_stage(self.kwargs)

        faces = self.get_filtered_faces(year, gradient, stage)

        if 'gradient' not in self.kwargs.keys() or self.kwargs['gradient'] == 'random':
            shuffle(faces)
        return faces

    def parse_year(self, url_kwargs):
        """returns the year parsed from the URL as a keyword
        argument."""
        if 'year' not in url_kwargs.keys() or url_kwargs['year'] == 'all':
            year = 'all'
        else:
            year = int(url_kwargs['year'])

        # set updated year attribute on class for return context
        self.year = year
        return year

    def parse_gradient(self, url_kwargs):
        """returns the gradient parsed from the URL as a keyword
        argument, converted into the appropriate queryset filter."""
        if 'gradient' not in url_kwargs.keys() or url_kwargs['gradient'] == 'random':
            self.gradient = 'random'
            gradient_filter = '?'
        elif url_kwargs['gradient'] == 'ascend':
            self.gradient = 'ascend'
            gradient_filter = 'gradient'
        else: # CASE: url_kwargs['gradient'] == 'descend'
            gradient_filter = '-gradient'
            self.gradient = 'descend'

        return gradient_filter
    
    def parse_stage(self, url_kwargs):
        """returns the stage parsed from the URL as a keyword
        argument."""
        if 'stage' not in url_kwargs.keys() or url_kwargs['stage'] == 'all':
            stage = 'all'
        else:
            stage = int(url_kwargs['stage'])

        # set updated year attribute on class for return context
        self.stage = stage
        return stage

    def get_filtered_faces(self, year, gradient, stage):
        """returns filtered queryset containing faces with the given
        year, gradient and stage."""

        if year == 'all':
            if stage == 'all':
                faces = list(Face.objects
                        .filter(size__gte=settings.MIN_FACE_SIZE)
                        .order_by(gradient))
            else: # a specific stage has been given
                faces = list(Face.objects
                        .filter(stage_num=stage, size__gte=settings.MIN_FACE_SIZE)
                        .order_by(gradient))
        else: # a specific year has been given
            if stage == 'all':
                faces = list(Face.objects
                        .filter(year=year, size__gte=settings.MIN_FACE_SIZE)
                        .order_by(gradient))
            else: # a specific stage has also been given
                faces = list(Face.objects
                        .filter(year=year, stage_num=stage, size__gte=settings.MIN_FACE_SIZE)
                        .order_by(gradient))
        return faces

    def get_context_data(self, **kwargs):
        context = super(CyclistGalleryView, self).get_context_data(**kwargs)
        context['year'] = self.year
        context['gradient'] = self.gradient
        context['stage'] = self.stage
        return context

def get_num_faces(min_size):
    """returns the total number of faces with the 
    specified minimum size."""
    faces_in_2012 = list(Face.objects.filter(year=2012, size__gte=min_size).order_by('gradient'))
    faces_in_2013 = list(Face.objects.filter(year=2013, size__gte=min_size).order_by('gradient'))
    faces_in_2014 = list(Face.objects.filter(year=2014, size__gte=min_size).order_by('gradient'))
    faces_in_2015 = list(Face.objects.filter(year=2015, size__gte=min_size).order_by('gradient'))
    
    num_faces = {
            '2012': {'num_faces': len(faces_in_2012),
                     'max_gradient': faces_in_2012[-1].gradient,
                     'min_gradient': faces_in_2012[0].gradient},
            '2013': {'num_faces': len(faces_in_2013),
                     'max_gradient': faces_in_2013[-1].gradient,
                     'min_gradient': faces_in_2013[0].gradient},
            '2014': {'num_faces': len(faces_in_2014),
                     'max_gradient': faces_in_2014[-1].gradient,
                     'min_gradient': faces_in_2014[0].gradient},
            '2015': {'num_faces': len(faces_in_2015),
                     'max_gradient': faces_in_2015[-1].gradient,
                     'min_gradient': faces_in_2015[0].gradient},
                     }
    return num_faces
 

faces/templates/faces/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Grimaces </title>
  <meta name="description" content="grimaces information page">
  <meta name="author" content="Samuel Albanie">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'faces/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'faces/css/skeleton.css' %}">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static 'faces/images/favicon.png' %}">

</head>
	<body>

	  <!-- Primary Page Layout
	  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
	  <div class="container">
	    <div class="row">
	      <div class="one-half column" style="margin-top: 20%">
		<h4>Grimaces dataset</h4>
		<p>The grimaces dataset consists of a collection of faces, together with the gradient of the racing surface extracted from footage of the Tour de France, running between 2012 and 2015.</p>
		</div>	
	     </div>
	    <div class="row">
		 <div class="one-half column">
			<h5>Statistics</h5>	

			<p>The dataset contains a total of {{ num_total_faces }} faces, which are distributed by year as follows:</p>
		<table class="u-full-width">
		  <thead>
		    <tr>
		      <th>Year</th>
		      <th>Number of faces</th>
		      <th>Gradient range</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td>2012</td>
		      <td>{{ num_faces_2012 }}</td>
		      <td>{{ min_gradient_2012 }}% to {{ max_gradient_2012 }}%</td>
		    </tr>
		    <tr>
		      <td>2013</td>
		      <td>{{ num_faces_2013 }}</td>
		      <td>{{ min_gradient_2013 }}% to {{ max_gradient_2013 }}%</td>
		    </tr>
		    <tr>
		      <td>2014</td>
		      <td>{{ num_faces_2014 }}</td>
		      <td>{{ min_gradient_2014 }}% to {{ max_gradient_2014 }}%</td>
		    </tr>
		    <tr>
		      <td>2015</td>
		      <td>{{ num_faces_2015 }}</td>
		      <td>{{ min_gradient_2015 }}% to {{ max_gradient_2015 }}%</td>
		    </tr>
		  </tbody>
		</table>
		</div>
		 <div class="one-half column" style="margin-top: 10%">
			{{ chart | safe}}
		</div>
	</div>
	    <div class="row">
		 <div class="one-half column">
		<h5>Experiments</h5>	
    <p>The dataset is being used to train a number of CNNs to perform gradient classification given a face as input. Years 2012 and 2013 are used for training and validation, while 2014 is used for testing. Results can be seen <a href="{% url 'faces:experiments' %}">here</a>.</p>
	      </div>
		 <div class="one-half column">
        <h5>Related Work</h5>	
        <p>Facial expression analysis is receiving a lot of attention at the moment. An overview of some relevant work is given <a href="{% url 'faces:related-work' %}">here</a>.</p>
            </div>
    </div>
	    <div class="row">
		 <div class="one-half column">
		<h5>Gallery</h5>	
		<p>Each face has a minimum size of {{ min_face_size }} pixels. The faces can be viewed <a href="{% url 'faces:cyclists-all' %}">here</a>.</p>
	      </div>
		 <div class="one-half column">
		<h5>Progress</h5>	
    <p>Weekly targets and progress reports can be viewed <a href="{% url 'faces:progress' %}">here</a>.</p>
	      </div>
      </div>
  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>